bilelmoussaoui/Hardcode-Tray

database/scripts/spotify
script.py

Ok that was easy. It still happens that the wrong icon is taken, this can only be circumenvented by using a different name for the panel icon (`spotify-client-panel.svg` for example) Since @Foggalong wants to do this anyway, I think it's possible to create a PR at Numix with the corresponding symlinks. If that happens we can change `spotify.txt` accordingly.

More spotify fixes

---

script.py

A few changes which results in quicker & cleaner script \O/
* Thought it was a little bit odd that detection for Pantheon was done through the OS but everything else was done through the DE. Did a bit of digging and found a way to detect Pantheon that used the already used `environ.get()` function from the `os` module. This allowed for the deletion of several OS centric variables, simplification of the 24px icon catch, and removal of the platform module from the import list.
* Now function specific importing is done both `is_dir(d)` and `is_file(f)` are no longer needed as user defined functions because it's actually quicker to just call the base function.
* Because it's only used once, `username` can be safely integrated into `userhome`.

Pantheon detection & minor cleanup

---

script.py

* After the last commit it dawned on me that the script is detecting what desktop enviroment the user is using, even though it only really needs to check for XFCE or Pantheon. I gutted all of superfluous stuff and shortened the function name to make it generally a bit lighter.
* Various changes to make the script follow the [PEP8 Styleguide](https://www.python.org/dev/peps/pep-0008/). These include:
* Removed trailing spaces
* Comments formatted `# COMMENT`
* Inline comments separated by 2 spaces
* 2 newlines between each definition
* Spaces around operators
* Spaces in comma lists (`item1, item2, item3`)
The one thing from PEP8 I haven't fixed is the line limit of 79 characters because it would require a bit more work in restructuring the functions.
Together these changes mean the line …

Optimisations and PEP8 compliance

---

README.md
database/google-chrome
database/owncloud
database/scripts/chrome
database/scripts/spotify
database/scripts/svg2png.py
script.py

The script was not executable, and since the destination file is meant to be a `png` file it is sufficient to just copy it, if the source file is a png as well. But cool work!

Fixes small errors in chrome script + a few other suggestions

---

database/scripts/spotify

A convert in spotify script is not really necessary, a cp is sufficient if source is png and destination is ico (it seems that the `ico` file in `resources.zip` is in fact just a funny named `png` file), therefore `cp is sufficient.

update spotify script

---

script.py

Catches problem when the source icon is png and destination is svg, because the script won't work in that case

failsafe for png to svg icons

---

script.py

Title says it. It seems that this folder is not created automatically after the new sni-qt-version is installed

Creates sni_qt_folder if it doesn't exist

---

database/scripts/qt-tray

The order was incorrect. Apart from that it works :+1:

Fixes symlinks for skype (and other qt apps)

---

script.py

For me this works great:) If the script fails it outputs the error message the script returns. I had to replace call by Popen, because only Popen allows to read from the PIPE

Adds error message when script did not work

---

database/scripts/qt-tray
script.py

The symlink function raises an error when the file does already exist. Therefore removing it beforehand is necessary

Catches error when symlink tried to symlink to existing file

---

database/scripts/chrome
database/scripts/data_pack.py
database/scripts/spotify
script.py

Ok, it works now. Had a few problems because you switched from relative to absolute paths for the chrome script. 
Btw. Can you enlighten me, what the counter (`i`) in the get_apps_informations functions is for? Seems to be useless for me

unpacks only once

---

README.md

I found the solution for #104! As of v1.0.16-1 it would seem that the svg2png function also depends on `cairocffi` which isn't install ed automatically as part of `cairosvg`

New dependency - fixes #104

---

database/scripts/data_pack.py

This pull request automatically fixes all occurrences of the following issue:
Issue type: [Prefer `format()` over string interpolation operator](https://www.quantifiedcode.com/app/issue_class/4ACGxFj1)
Issue details: [https://www.quantifiedcode.com/app/project/gh:bil-elmoussaoui:Hardcode-Tray?groups=code_patterns/%3A4ACGxFj1](https://www.quantifiedcode.com/app/project/gh:bil-elmoussaoui:Hardcode-Tray?groups=code_patterns/%3A4ACGxFj1)
To adjust the commit message or the actual code changes, just [rebase](https://git-scm.com/docs/git-rebase) or [cherry-pick](https://git-scm.com/docs/git-cherry-pick) the commits.
For questions or feedback reach out to cody@quantifiedcode.com.
Legal note: We won't claim any copyrights on the code changes.
Cheers,
[Cody - Your code quality …

Fix "Prefer `format()` over string interpolation operator" issue

---

database/telegram.json

When Telegram-desktop installed from ppa, this is usual path (ubuntu 14.04+)

Add default telegram path (installed from ppa)

---

database/telegram.json

See : https://github.com/telegramdesktop/tdesktop/issues/107#issuecomment-254517701
Fix #335

Add new Telegram path

---

database/keebuntu.json
database/keepass.json

`keeubuntu` is required for changing the tray icon.

Add support for keebuntu tray icon

---

src/path.py

In case of my path, dropbox downloads its files at
/home/usrid/.dropbox-dist/dropbox-lnx.x86_64-26.4.24
which makes the current code fail. A better way for this probably is to split by "/" and then check that the fith elem starts with drobox.
Here's a PR that does that.

Fixes dropbox path issue

---

data/database/webtorrent-desktop.json

It's electron app, but asar unpacked (for icons only). For right work need use with `StartupWMClass=WebTorrent`, because desktop icon show as tray icon without WMClass...

WebTorrent Desktop fix

---

data/database/wire.electron.json

Compatibility fix for Wire installed from the Solus main repo.
[https://solus-project.com/](https://solus-project.com/)

Add Solus compatibility for Wire

---

README.md

On arch, `pkg-config` is needed for `sni-qt-patched`. It is a part of the `base-devel` group.

Adding `base-devel` to installation instructions

---

data/database/rto-proxy.electron.json

Electron application for unblock IP's trackers on bigger Russian torrent tracker Rutracker.org
Github page: https://github.com/RutrackerOrg/rutracker-proxy

RuTracker Proxy support

---

data/database/qjoypad.json
data/database/vivaldi.json

Qt5 application, but use tray icon from hicolor icon theme and app icon from system icon theme.
https://github.com/panzi/qjoypad/blob/6e7bfa8a063a798efd4ea0eaa750885be892e224/src/layout.cpp#L39
https://github.com/panzi/qjoypad/blob/6e7bfa8a063a798efd4ea0eaa750885be892e224/src/config.h.in#L12
More info here:
https://github.com/PapirusDevelopmentTeam/papirus-icon-theme/issues/1458

QJoyPad support & Vivaldi 1.15

---

data/database/skypeforlinux.json

Four new tray icons for "away" status introduced with skypeforlinux 8.33

Add Skypeforlinux 8.33 away tray icons

---

data/database/telegram.json

Seems that Telegram changed its icon names:

fix telegram icons

---

README.md

It also removes `sni-qt` from installation command for Ubuntu because we stop providing the patched sni-qt for Ubuntu 19.10.

Added repositories with daily builds for Fedora 29+/Rawhide, Debian 10

---

README.md
circle.yml
tests/pylint.sh

- Removed discontinued repository for openSUSE
- Updated URLs to Debian/Fedora repos
- Improved commands for adding repos to support all available versions of the distos
- Fixed `pip3: command not found` error in tests
- Disabled pylint to make tests clear

Update repos for Debian/Fedora. Delete repo for openSUSE

---

HardcodeTray/modules/svg/svg.py

See #639.
Using a context makes sure that the `NamedTemporaryFile` used in `to_bin` is only closed when we are done reading its content, and prevents an early deletion of the file if it gets garbage-collected before the results of `to_png` are read.

Fix issue related to `NamedTemporaryFile` in `svg` module (fixes #639)

---

README.md

Obvious, but for someone automatically copy-pasting the instructions, this could cause some issues if you try to compile it outside the source folder.

Added a little cd line for the compilation

---

data/database/discord.electron.json

This morning I got a Discord update (a new `.deb` package) so my custom tray icon was gone. Tried to fix it as usual but Hardcode-Tray reported "no apps to fix". Changing the version number in `data/database/discord.electron.json` fixed the issue and Hardcode-Tray correctly replaced my tray icon.

update Discord version to 0.0.14

---

data/database/discord.electron.json

Another Discord update broke the tray icon today. Updating `/data/database/discord.electron.json` as before, and rebuilding/reinstalling, I replaced the tray icon successfully with my own custom icon once again.

updated Discord to version 0.0.15

---

HardcodeTray/utils.py

Fixes #704, #637, #646
Some Electron apps such as Mattermost Desktop 5.0.0 contain a directory named "offset" in their app.asar files, which is treated in code as a `dict` of `dict`s representing files and subdirectories. Hardcode Tray expects a string for actual offset values before recalculating them. This fix adds a check to make sure that it only performs the said action on offset numbers.
~~However, another bug came up as I completed this. For some reason, Hardcode Tray could no longer find unread and mentioned tray icons for Mattermost Desktop 5.0.0, leaving them intact as a result. This PR is complete once I have a fix for that side effect pushed into this PR and no further side effects appear.~~
**Edit:** The side effect was rather caused by typos in the proposed changes to …

Fix crash when calculating Asar file content offsets

---

HardcodeTray/modules/path.py
HardcodeTray/path.py
data/database/discord.electron.json

This PR adds a callback for Discord. Simply put it adds `{discord}` variable instead of the version number in the path like `{userhome}/.config/discord/{discord}/modules/discord_desktop_core/`.
It will be useful for fixing #685
Not tested yet.

Added Discord callback

---

data/database/caprine.electron.json

This adds the paths used by the RPM package provided in the [dusansimic/caprine COPR](https://copr.fedorainfracloud.org/coprs/dusansimic/caprine/).

Add mising caprine.electron paths
