bilelmoussaoui/Hardcode-Tray

script.py
Improves detection of desktop environment, because it wasn't working before correctly. Should be more flexible now, although there's no really good way to do this...
=> Improves detection of DE

script.py
Makes the script executable and therefore adds python shebang at beginning of file
=> Makes script executable

script.py
=> Fixes missing period + a few typos

script.py
I think this should help if the `else` comes up. This way this app should just be ignored
=> Catches error

database/grive-tools.txt
I guess this was not intentional, was it?
=> Fixes typo in grive-tools.txt

README.md
Readme had still the light dark in it
=> Adapts Readme

database/radiotray.txt
=> fixes typo in radiotray.txt

database/scripts/spotify, database/spotify.txt, db.csv, script.py
Adds spotify support. Seems to work :) One thing however: its unfortunately necessary to have inkscape installed because imagemagick is not able to convert svg to ico properly
=> Adds spotify support

database/scripts/spotify
This is the last error, I promise. It works fine now:)
=> Another small error

script.py
* use `from a import b` rather than `import a`
* only imports the functions you need rather than everything
* cleaner function/variable names in the code
* dropped unneeded signature variables
* removed `import pwd` from deprecated feature
=> Module cleanup

script.py
An import was missing for subprocess.call needed in line 156
=> Adds missing import

database/scripts/owncloud
If there are other sni-qt apps that uses the same location, this script (or a symlink to it) should work as well. This is really an easy bash script :)
=> Adds owncloud bash script

database/scripts/owncloud
Ah you said you wanted a symlink, you were too fast in merging :)
=> A symlink it is

script.py
=> Fixes sni_qt folder not created

script.py
=> fixes bug from missing extensions

script.py
Even if the file was invalid, the script continued and printed a success message
=> Better error handling

script.py
I cleaned the code up a little bit, because we were overwriting a variable from a for loop, which is considered bad programming ...
=> Small fixes in code

script.py
It's probably a better idea to strip the variables right after reading them...
=> Do space stripping before

script.py
Only do backup if there's a corresponding theme icon, otherwise its pointless
=> Only backup if it is needed

script.py
I changed the reverting to a more simple way (just a suggestion). The script now doesn't need a backup-folder but it generates a `.bak` file in the folder where the original icon is stored. Works flawlessly on my machine for all scenarios
=> Changes reverting to a more simple way

script.py
We can delete the whole sni_qt folder at once, that's way easier
=> Delete sni_qt folder at once

database/google-chrome, database/scripts/qt-tray, database/spotify, script.py
Th backup functions were pretty much redundant, I added a third column to the database files in order to combine these two functions + I replaced some tabs with spaces
=> Only one single backup function

README.md, database/scripts/qt-tray, database/scripts/svg2png.py, script.py
=> Add Inkscape support!

database/scripts/teamviewer, database/teamviewer, script.py
=> Symlinks for teamviewer

database/scripts/svgtopng.py, database/scripts/whatsie, database/whatsie, db.csv
Fixes #147 . I'm actually pretty proud about the coding I did here. No temporary files are necessary, everything is done on the fly, and I was able to introduce an iterative function :)
=> Adds support for whatsie

README.md, hardcode-tray, install.sh, uninstall.sh
=> Implements scritp installation

script.py
Just removed a space before the comma
=> Minor Grammar Fix

database/telegram.json
adding the path for telegram compiled from source on arch ([AUR](https://aur.archlinux.org/packages/telegram-desktop/))
=> additional app path for telegram on arch (source version)

database/slack.json
Added paths for the [slack-desktop](https://aur.archlinux.org/packages/slack-desktop/) AUR package
=> Make slack.json compatible with arch

database/harmony.json
=> fix harmony

database/gpmdp.json
=> fix paths in gpmdm

database/cisco-anyconnect.json
Added support for Cisco AnyConnect hardcoded icons for Papirus Icon Theme.
https://github.com/PapirusDevelopmentTeam/papirus-icon-theme/issues/313
=> Cisco AnyConnect support

database/gpmdp.json
I added the path where the AUR package installs Google Play Music Desktop Player.
Thank you for making a awesome tool 🙌
=> Added support for GPMDP installed through AUR

database/franz.json
@bil-elmoussaoui Can you take a look at this. I'm not 100% sure I did everything right there (esp. with the symlinks)
=> Fixes franz attention icons once and for all

database/wire.json, database/wire_elec.json
Fix #351 
Credits to @dwellerattic
=> Fix issue Wire icon

data/database/synergy.json
https://github.com/PapirusDevelopmentTeam/papirus-icon-theme/issues/543
=> Synergy support

data/database/skypeforlinux.json
=> Add SkypePreview Support

data/database/gajim.json
Gajim use multiple icon sets. Replace the tray icons in all of them :p
=> add support for Gajim

data/database/gajim.json
=> Remove duplicate symlinks

data/database/discord.json
=> Updated Discord support

data/database/rocketchat.json
https://github.com/PapirusDevelopmentTeam/papirus-icon-theme/issues/945
=> RocketChat support

data/database/whatsapp.json
=> add whatsapp-desktop 0.4.2+ support

data/database/openbazaar2client.json
Electron app, but resources not packed.
https://github.com/OpenBazaar/openbazaar-desktop
=> Support OpenBazaar 2.0 Desktop Client

data/database/yakyak.json
=> update yakyak database

data/database/riot.electron.json
https://github.com/PapirusDevelopmentTeam/papirus-icon-theme/issues/1282
=> add Riot support #525

data/database/irccloud.electron.json
electron app with packed asar. resources from DEB-package
=> IRCCloud support #523

data/database/ao.electron.json
electron app with packed asar. resources & paths from DEB-package
=> Ao support #516

license/GPL
=> Update GPL license text

data/database/odrive.electron.json
Electron app.
https://github.com/liberodark/ODrive
=> support OpenDrive

data/database/guitarix.json
=> Support Guitarix

README.md
https://launchpad.net/~papirus/+archive/ubuntu/hardcode-tray
=> Reincarnation of daily builds PPA

data/database/electron-mail.electron.json, data/database/yate.json
http://yateclient.yate.ro/
https://github.com/PapirusDevelopmentTeam/papirus-icon-theme/issues/1687
=> Support Yate Client & ElectronMail

data/database/franz.electron.json
=> Update Franz 5.1.0

data/database/skypeforlinux.json
There are a new bucket if icons needed to be replaced.
=> skypeforlinux newIcons support

data/database/minetime.json
Electron app, but with unpacked asar.
https://minetime.ai/
https://github.com/PapirusDevelopmentTeam/papirus-icon-theme/issues/1750
=> MineTime support

wewechat.json
Support for [wewechat](https://github.com/trazyn/weweChat)
=> wewechat support

HardcodeTray/tools.py
$DESKTOP_SESSION can report gnome as gnome-xorg
=> Add gnome-xorg to the DE list

data/database/motrix.json
Fixed tray icon for AUR packages of Motrix.
=> Add Motrix (AUR version)

data/database/teams-insiders.json
teams-insiders is the same application as teams, but installs under a different directory, as a separate package
=> Added teams-insiders to database

data/database/joplin.json
The AUR package for Joplin desktop APP has a new install location; adding it to the database.
=> New Joplin desktop APP install location (AUR ver.)

HardcodeTray/modules/svg/svg.py
=> Reopen converted temp PNG file before reading it

data/database/skype.json
Add initial support for Skype on Flatpak
=> Skype Flatpak support

data/database/moderndeck.electron.json
Updating moderndeck.electron.json with new path.
=> ModernDeck
